# VotingPlugin by Ben12345rocks
# Main Config
# See wiki for help: 
# https://github.com/Ben12345rocks/VotingPlugin/wiki

# Wether debug info will be displayed
Debug: false

# Broadcast votes
BroadcastVote: true

# Give players with permission "VotingPlugin.remindupdate" update reminder
# When a update is available on login
UpdateReminder: true

# Let players who never joined before vote
AllowUnjoined: false

# Disable Montly Top Voter Awards
DisableTopVoterAwards: true

# If true /vote will open VoteURL GUI
VoteURLDefault: false

# If true, plugin will automaticly generate votesites
# Disable if you experience issues with sites being created
AutoCreateVoteSites: true

# Number of seconds between background updates
# Default: 600 (10 minutes)
BackgroundTaskDelay: 600