# VotingPlugin by Ben12345rocks
# Main Config
# See wiki for help: 
# https://github.com/Ben12345rocks/VotingPlugin/wiki

# Wether debug info will be displayed
Debug: false

# Broadcast votes
BroadcastVote: true

# Let players who never joined before vote
AllowUnjoined: false

# Enable Montly Top Voter Awards
TopVoterAwards: false

# If true /vote will open VoteURL GUI
VoteURLDefault: false

# If true, plugin will automaticly generate votesites
# Disable if you experience issues with sites being created
# randomly
AutoCreateVoteSites: true

# Number of seconds between background updates
# Default: 600 (10 minutes)
BackgroundTaskDelay: 600