# VotingPlugin by Ben12345rocks
# Main Config
# To set Format, see Format.yml
# Set Bonus Reward in BonusReward.yml
# Set VoteSites in the folder VoteSites
# See wiki for help: 
# https://github.com/Ben12345rocks/VotingPlugin/wiki

# Wether debug info will be displayed
Debug: false

# Broadcast votes
BroadcastVote: true

# Remind players when they can vote
RemindVotes: true

# Give players with permission "VotingPlugin.remindupdate" update reminder
# When a update is available on login
UpdateReminder: true

# Let players who never joined before vote
AllowUnjoined: false

# Disable Montly Top Voter Awards
DisableTopVoterAwards: true

# If true /vote will open VoteURL GUI
VoteURLDefault: false

# If true, plugin will not automaticly
# generate votesites
# Useful if you experience issues with sites being created
DisableAutoCreateVoteSites: false

# Sound on vote
VoteSound:
  # Enable or Disable Sound
  Enabled: false
  # Sound to play
  # 1.9 Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # 1.8: https://jd.bukkit.org/org/bukkit/Sound.html 
  Sound: 'BLOCK_ANVIL_USE'
  # Volume
  # Range: 0.0 to 1.0
  Volume: 1.0
  # Pitch
  # Range: 0.0 to 1.0
  Pitch: 1.0
  
# Play particle effect on vote
# 1.10 Effects can be found here:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
VoteEffect:
  Enabled: false
  Effect: 'EXPLOSION'
  Data: 0
  Particles: 10
  Radius: 5
  
# Title to run on vote
# Requires TitleAPI (and all of its requirements)
# Download here: 
# https://www.spigotmc.org/resources/api-titleapi-1-7-1-8-1-9.1047/
VoteTitle:
  Enabled: false
  Title: 'Thanks for voting!'
  TitleColor: red
  SubTitle: 'You voted on %votesite%'
  SubTitleColor: blue
  FadeIn: 10
  ShowTime: 50
  FadeOut: 10