# VotingPlugin by Ben12345rocks
# Main Config
# To set Format, see Format.yml
# Set Bonus Reward in BonusReward.yml
# Set VoteSites in the folder VoteSites
# See wiki for help: 
# https://github.com/Ben12345rocks/VotingPlugin/wiki

# Wether debug info will be displayed
Debug: false

# Broadcast votes
BroadcastVote: true

# Remind players when they can vote
RemindVotes: true

# Give players with permission "VotingPlugin.remindupdate" update reminder
# When a update is available on login
UpdateReminder: true

# Let players who never joined before vote
AllowUnjoined: false

# Disable Montly Top Voter Awards
DisableTopVoterAwards: true

# Sound on vote
VoteSound:
  # Enable or Disable Sound
  Enabled: false
  # Sound to play
  Sound: ''
  # Volume
  # Range: 0.0 to 1.0
  Volume: 1.0
  # Pitch
  # Range: 0.0 to 1.0
  Pitch: 1.0

