# VotingPlugin by Ben12345rocks
# Main Config
# To set Format, see Format.yml
# To add or edit vote sites, see VoteSites.yml
# Set Bonus Reward in BonusReward.yml

# Wether debug info will be displayed
Debug: false

# Broadcast votes
BroadcastVote: true

# Remind players when they can vote
RemindVotes: true

# Give players a bonus reward when all votes have been complete
AllVotesBonus: false

# Give players with permission "VotingPlugin.remindupdate" update reminder
# When a update is available on login
UpdateReminder: true

# Let players who never joined before vote
AllowUnjoined: true

