# VotingPlugin by Ben12345rocks
# Main Config
# See wiki for help: 
# https://github.com/Ben12345rocks/VotingPlugin/wiki

# Broadcast votes
BroadcastVote: true

# Let players who never joined before vote
# Recommend: False (Will prevent creating random user data files)
AllowUnjoined: false

# If true /vote will open VoteURL GUI
VoteURLDefault: false

# If true, plugin will send scoreboards on some commands
SendScoreboards: true

# If true, plugin will automaticly generate votesites
# Disable this if you experience issues with sites being 
# created randomly
AutoCreateVoteSites: true

# Number of seconds between background updates
# Default: 600 (10 minutes)
BackgroundTaskDelay: 600

# Wether or not to log every vote to a file
LogVotesToFile: false
