# VotingPlugin by Ben12345rocks
# Main Config
# See wiki for help: 
# https://github.com/Ben12345rocks/VotingPlugin/wiki

# Wether debug info will be displayed
Debug: false

# Broadcast votes
BroadcastVote: true

# Let players who never joined before vote
AllowUnjoined: false

# Enable Montly Top Voter Awards
TopVoterAwards: false

# If true /vote will open VoteURL GUI
VoteURLDefault: false

# If true, plugin will automaticly generate votesites
# Disable if you experience issues with sites being created
# randomly
AutoCreateVoteSites: true

# Number of seconds between background updates
# Default: 600 (10 minutes)
BackgroundTaskDelay: 600


# --------- Voting Effects --------
# The following will be sent to voter when the voter is online
# You can also send the following in each reward file if you wish
# This will only run once if player has voted offline, regardless of number of votes

# Title to send to voter
# Requires TitleAPI (and all of its requirements)
# Download here: 
# https://www.spigotmc.org/resources/api-titleapi-1-7-1-8-1-9.1047/
Title:
  Enabled: false
  Title: 'Thanks for voting!'
  TitleColor: red
  SubTitle: 'You voted on %votesite%'
  SubTitleColor: blue
  FadeIn: 10
  ShowTime: 50
  FadeOut: 10
  
# Sound to voter
Sound:
  # Enable or Disable Sound
  Enabled: false
  # Sound to play
  # 1.9 Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # 1.8: https://jd.bukkit.org/org/bukkit/Sound.html 
  Sound: 'BLOCK_ANVIL_USE'
  # Volume
  # Range: 0.0 to 1.0
  Volume: 1.0
  # Pitch
  # Range: 0.0 to 1.0
  Pitch: 1.0
  
# Play particle effect to voter
# 1.10 Effects can be found here:
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
Effect:
  Enabled: false
  Effect: 'EXPLOSION'
  Data: 0
  Particles: 10
  Radius: 5