SendVotesToAllServers: true
SendToOnlineServer: false
# MYSQL INFO --------------------------
Host: ''
# Default port is 3306
Port: 3306 
Database: ''
Username: ''
Password: ''
# Max number of connections
MaxConnections: 1
# Maxium size of caching mysql
# -1 for no limit
# Affecting this value may affect performance
MaxSize: -1
# Table name prefix, for use with mutliple servers
Prefix: ''
#UseSSL: true
#########################################