# STILL A WORK IN PROGRESS, USE AT YOUR OWN RISK
# 
# Set bungeecoord to true on servers on the network
# Set server name in each server related to what it is on bungee
#
# Have a reward on each server
SendVotesToAllServers: true
# Have a reward on 1 server on the network
SendToOnlineServer: false 
# MYSQL Required
# MYSQL INFO --------------------------
Host: ''
# Default port is 3306
Port: 3306 
Database: ''
Username: ''
Password: ''
# Max number of connections
MaxConnections: 1
# Maxium size of caching mysql
# -1 for no limit
# Affecting this value may affect performance
MaxSize: -1
# Table name prefix, for use with mutliple servers
Prefix: ''
#UseSSL: true
#########################################