# VotingPlugin by Ben12345rocks
# Main Config
# See wiki for help: 
# https://github.com/Ben12345rocks/VotingPlugin/wiki

# Broadcast votes
BroadcastVote: true

# Let players who never joined before vote
# Recommend: False (Will prevent creating random user data files)
AllowUnjoined: false

# If true, plugin will send scoreboards on some commands
SendScoreboards: true

# If true, plugin will automaticly generate votesites
# Disable this if you experience issues with sites being 
# created randomly
AutoCreateVoteSites: true

# Wether or not to log every vote to a file
# Use this if you wanna track player votes
# Not recommended though
LogVotesToFile: false

# Configuration for VoteReminding
# By default this should be all setup to work
# as long as vote delays are done properly
VoteReminding:
  # Enable vote reminding
  # This will remind player when he can vote on all sites
  # Requires VoteDelay's to be setup properly
  # Use /vote next to see when you can be reminded
  # Players require the perm "VotingPlugin.Login.RemindVotes" or "VotingPlugin.Player"
  Enabled: true

  # Wether or not to remind only once when the player can vote
  # Does not apply to login reminds.
  RemindOnlyOnce: true

  # Will remind player on login if he can vote
  # Ignores value above
  RemindOnLogin: true

  # Delay to remind votes in minutes
  # Only works if above is false
  RemindDelay: 30

  # Run reward files on remind
  # By default, the reward file will be created for you
  # and have the default message
  # Edit the message at AdvancedCore/Rewards/Remind.yml (or any other reward listed)
  # Can add titles and more in the reward file
  Rewards:
  - 'Remind'
  
Commands:
  # Wether or not the following commands will open GUIs rather than display text
  UseGUI:
    Today: true
    TopVoter: true
    Last: true
    Next: true
    Total: true
    Vote: true


