name: ${project.name}
version: ${project.version}
main: com.Ben12345rocks.VotingPlugin.Main
description: Highly Customizable Voting Listener!
website: https://www.spigotmc.org/resources/votingplugin.15358/
author: Ben12345rocks
softdepend: [AdvancedCore]
commands:
  vote:
    description: Vote command
  adminvote:
    description: Admin commands for VotingPlugin
  av:
    description: Admin commands for VotingPlugin
  votehelp:
    description: See access to a list of commands, Formated in Format.yml
    aliases: vhelp
  votetotal:
    description: See totals of votes
    aliases: vtotal
  votelast:
    description: See the last time you voted
    aliases: vlast
  votenext:
    description: See when you can vote next
    aliases: vnext
  votetop:
    description: See top voters
    aliases: vtop
  voteinfo:
    description: See player info
    aliases: vinfo
  votetoday:
    description: See who voted today
    aliases: vtoday
  votegui:
    description: Open VoteGUI
    aliases: vgui
  voteurl:
    description: Open VoteURL
    aliases: vurl
  votereward:
    description: Open VoteReward GUI
    aliases: vreward
  vote?:
    description: View Help
    aliases: v?
  voteparty:
    description: A command
    aliases: vparty
  voteshop:
    description: A command
    aliases: vshop
  votebest:
    description: A command
    aliases: vbest
  votestreak:
    description: A command
    aliases: vstreak
  votepoints:
    description: A command
    aliases: vpoints
  votegivereward:
    description: A command
  voteselectChoiceReward:
    description: A command
  adminvotehelp:
    description: Open adminvote help
    aliases: avhelp
  adminvote?:
    description: Open adminvote help
    aliases: av?
  adminvoteconvert:
    description: A command
  adminvotereport:
    description: Command Alias
    aliases: avreport
  adminvoteperms:
    description: Command Alias
    aliases: avperms
  adminvoteDownload:
    description: Command Alias
    aliases: avdownload
  adminvotereload:
    description: Command Alias
    aliases: avreload
  adminvoteversion:
    description: Command Alias
    aliases: avversion
  adminvotesites:
    description: Command Alias
    aliases: avsites
  adminvoterewards:
    description: Command Alias
    aliases: avrewards
  adminvotereward:
    description: Command Alias
    aliases: avreward
  adminvoteuuid:
    description: Command Alias
    aliases: avuuid
  adminvotereset:
    description: Command Alias
    aliases: avreset
  adminvotevotesite:
    description: Command Alias
    aliases: avvotesite
  adminvoteconfig:
    description: Command Alias
    aliases: avconfig
  adminvoteserverdata:
    description: Command Alias
    aliases: avserverdata
  adminvotesettotal:
    description: Command Alias
    aliases: avsettotal
  adminvoteupdatecheck:
    description: Command Alias
    aliases: avupdatecheck
  adminvotevote:
    description: Command Alias
    aliases: [avvote, fakevote]
  adminvoteTriggerPlayerVoteEvent:
    description: Command Alias
    aliases: avTriggerPlayerVoteEvent
  adminvotesetpoints:
    description: Command Alias
    aliases: avsetpoints
  adminvoteaddpoints:
    description: Command Alias
    aliases: avaddpoints
  adminvotegui:
    description: Command Alias
    aliases: avgui
  votesetrequestmethod:
    description: Command Alias
    aliases: [vsetrequestmethod, setrequesetmethod]
  adminvotegivereward:
    description: Command Alias
    aliases: avgivereward
  adminvoteusers:
    description: Command Alias
    aliases: avusers
  adminvoteClearTotal:
    description: Command Alias
    aliases: avClearTotal
  adminvoteConvertFromData:
    description: Command Alias
    aliases: avConvertFromData
  adminvoteClearTotal:
    description: Command Alias
    aliases: avClearTotal
  adminvoteBackgroundUpdate:
    description: Command Alias
    aliases: avBackgroundUpdate
  adminvoteClearCache:
    description: Command Alias
    aliases: avClearCache
permissions:
  VotingPlugin.Player:
    description: Allows basic access player commands
    default: true
  VotingPlugin.Mod:
    description: Allows mod access player commands
  VotingPlugin.Admin:
    description: Allows admin access player commands
  VotingPlugin.Login.RemindVotes:
    description: Allows players to get remined on login if they can vote
    default: true
  VotingPlugin.Admin.Debug:
    description: Permission to view debug info ingame
  VotingPlugin.Signs.Create:
    description: Allows access to create signs
  VotingPlugin.TopVoter.Ignore:
    description: Allows you to be exempt from top voter
  